/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.*;
import static javax.swing.DropMode.INSERT;
import javax.swing.JOptionPane;

public class testing extends javax.swing.JFrame {

    /**
     * Creates new form testing
     */
    public testing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insertbtn = new javax.swing.JButton();
        Nametxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        showbtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        GetField = new javax.swing.JTextField();
        GetButton = new javax.swing.JButton();
        set = new javax.swing.JButton();
        setfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Editbtn1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        jPanel1.add(insertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 104, 38));

        Nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametxtActionPerformed(evt);
            }
        });
        jPanel1.add(Nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, 104, 39));

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 677, 192, 107));

        showbtn.setText("Show");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });
        jPanel1.add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 69, 61, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 69, 61, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 69, 61, -1));

        GetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetFieldActionPerformed(evt);
            }
        });
        jPanel1.add(GetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 106, 127, -1));

        GetButton.setText("Get");
        GetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 144, -1, -1));

        set.setText("set");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        jPanel1.add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 778, -1, -1));
        jPanel1.add(setfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 724, 109, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Editbtn1.setBackground(new java.awt.Color(0, 0, 0));
        Editbtn1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Editbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Editbtn1.setText("•••");
        Editbtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Editbtn1.setMaximumSize(new java.awt.Dimension(75, 20));
        Editbtn1.setMinimumSize(new java.awt.Dimension(75, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(Editbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Editbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public static Connection tools() throws SQLException, ClassNotFoundException { //SHORTCUT
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/testing", "root", "julius022104");
    return con;
}
    
    
    
    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        String name = Nametxt.getText();
        
        try{   //INSERTING DATA
            Connection con = tools();
            String sql = "INSERT INTO table1 (Name) VALUES (?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, name);
            pstmt.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Name inserted successfully");
                con.close();       
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace(); // Print the stack trace to diagnose any issues
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      }
        
        try{  //SHOW AFTER INSERTING
            Connection con = tools();
            Statement s = con.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM table1");

        StringBuilder records = new StringBuilder();
        while (rs.next()) {
            // Assuming you have a column named 'Name'
            String Name = rs.getString("Name");
            records.append(Name).append("\n");
        }

        // Set the formatted string to the JTextArea
        TextArea.setText(records.toString());

        con.close();   
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace(); // Print the stack trace to diagnose any issues
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      }
        
        
        
        
        
        
        
    }//GEN-LAST:event_insertbtnActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
         try{  //SHOWING DATA
            Connection con = tools();
            Statement s = con.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM table1");

        StringBuilder records = new StringBuilder();
        while (rs.next()) {
            // Assuming you have a column named 'Name'
            String Name = rs.getString("Name");
            records.append(Name).append("\n");
        }

        // Set the formatted string to the JTextArea
        TextArea.setText(records.toString());

        con.close();   
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace(); // Print the stack trace to diagnose any issues
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_showbtnActionPerformed

    private void NametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NametxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void GetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetFieldActionPerformed

    private void GetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetButtonActionPerformed
        
        
        try{  //SHOWING DATA
            Connection con = tools();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM table1");

        StringBuilder records = new StringBuilder();
        while (rs.next()) {
            // Assuming you have a column named 'Name'
            String Name = rs.getString("Name");
            records.append(Name).append("\n");
        }

        // Set the formatted string to the JTextArea
        TextArea.setText(records.toString());

        con.close();   
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace(); // Print the stack trace to diagnose any issues
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      }
        
        
        
        
        
        
        
    }//GEN-LAST:event_GetButtonActionPerformed

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
       String got = setfield.getText();
       
       here h = new here();
       h.here.setText(got);
       
       h.setVisible(true);
    }//GEN-LAST:event_setActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editbtn1;
    private javax.swing.JButton GetButton;
    private javax.swing.JTextField GetField;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton insertbtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton set;
    private javax.swing.JTextField setfield;
    private javax.swing.JButton showbtn;
    // End of variables declaration//GEN-END:variables
}
